### ISSUE TITLE
Unexpected token n in JSON at position 1118

### ISSUE THREAD

**Issue by FireController1847** [shardick/etcars-node-client#3]
This is all the error says, there's not much more information. It just spams this over and over.

```
Unexpected token n in JSON at position 1118
Unexpected token n in JSON at position 1118
Unexpected token n in JSON at position 1118
Unexpected token n in JSON at position 1118
Unexpected token n in JSON at position 1118
Unexpected token n in JSON at position 1118
```

**Comment by FireController1847** [comment]
Digging deeper into this, it appears that ETCars is sending some string data back without quotes? I'll continue investigating.

**Comment by FireController1847** [comment]
I've found the culprit: "oilPressure":-nan,

**Comment by felix-d1strict** [comment]
Will there be a fix for this?

**Comment by FireController1847** [comment]
My basic workaround is to add a replace statement before parsing the JSON string that replaces all "-nan" to 0. It's not the best solution but it did fix the issue temporarily. Hope that helps.

**Comment by felix-d1strict** [comment]
Thank you, we will try this.

**Comment by dowmeister** [comment]
Hi, the project has been discontinued.
