### ISSUE TITLE
Unexpected token in JSON at position 15270

### ISSUE THREAD

**Issue by felix-d1strict** [shardick/etcars-node-client#4]
This is all the error says, there's not much more information. It just spams this over and over. Like issue: https://github.com/shardick/etcars-node-client/issues/3

`Unexpected token in JSON at position 15270`

**Comment by doouz** [comment]
Same for me

`Unexpected token § in JSON at position 16133`
`Unexpected token ☻ in JSON at position 16789`

**Comment by dowmeister** [comment]
Hi, the project has been discontinued.
